export default {
  UniversityAdmin: {
    auth: {
      login: "auth/login/",
      currentUser: `/auth/current-user/`,
      updateProfile: `/auth/update-profile/`,
      changePassword: `/auth/change-password/`,
      resetPassword: `/auth/reset-password/`,
      resetComfirmPassword: `/auth/reset-password/confirm/`,
      logout: `/auth/logout/`,
    },
    adminUsers: {
      list: `/admin-users/`,
      details: (id) => `/admin-users/${id}/`,
      edit: (id) => `/admin-users/${id}/`,
      create: `/admin-users/`,
      delete: (id) => `/admin-users/${id}/`,
    },
    core: {
      University: {
        list: "/universities/",
        details: (id) => `universities/${id}`,
        edit: (id) => `universities/${id}`,
      },
      newsLetter: {
        list: "/newsletters/",
        subscription: "/newsletter-subscriptions/",
        details: (id) => `/newsletters/${id}/`,
        subscriptionDetails: (id) => `/newsletter-subscriptions/${id}/`,
        logs: "/newsletter-logs/",
        edit: (id) => `/newsletters/${id}/`,
        logDetail: (id) => `/newsletter-logs/${id}/`,
        subscriptionEdit: (id) => `/newsletter-subscriptions/${id}/`,
      },
      universities: "/universities",
    },
    events: {
      category: {
        list: "/event-categories/",
        details: (id) => `/event-categories/${id}/`,
        edit: (id) => `/event-categories/${id}/`,
        create: `/event-categories/`,
        delete: (id) => `/event-categories/${id}/`,
      },
      list: `/events/`,
      details: (id) => `/events/${id}/`,
      create: `/events/`,
      edit: (id) => `/events/${id}/`,
      delete: (id) => `/events/${id}/`,
    },
    facultiesAndDepartments: {
      faculties: {
        list: `/faculties/`,
        details: (id) => `/faculties/${id}`,
        create: `/faculties/`,
        edit: (id) => `/faculties/${id}`,
        delete: (id) => `/faculties/${id}`,
      },
      facultyLeadershipRoles: {
        list: `/faculty-leadership-roles/`,
        details: (id) => `/faculty-leadership-roles/${id}`,
        create: `/faculty-leadership-roles/`,
        edit: (id) => `/faculty-leadership-roles/${id}`,
        delete: (id) => `/faculty-leadership-roles/${id}`,
      },
      departments: {
        list: `/departments/`,
        details: (id) => `/departments/${id}`,
        create: `/departments/`,
        edit: (id) => `/departments/${id}`,
        delete: (id) => `/departments/${id}`,
      },
      academicStaffRoles: {
        list: `/academic-staff-roles/`,
        details: (id) => `/academic-staff-roles/${id}`,
        create: `/academic-staff-roles/`,
        edit: (id) => `/academic-staff-roles/${id}`,
        delete: (id) => `/academic-staff-roles/${id}`,
      },
      facultyNewSlides: {
        list: `/faculty-news-slides/`,
        details: (id) => `/faculty-news-slides/${id}`,
        create: `/faculty-news-slides/`,
        edit: (id) => `/faculty-news-slides/${id}`,
        delete: (id) => `/faculty-news-slides/${id}`,
      },
      facultyNews: {
        list: `/faculty-news/`,
        details: (id) => `/faculty-news/${id}`,
        create: `/faculty-news/`,
        edit: (id) => `/faculty-news/${id}`,
        delete: (id) => `/faculty-news/${id}`,
      },
      facultyHighlights: {
        list: `/faculty-highlights/`,
        details: (id) => `/faculty-highlights/${id}`,
        create: `/faculty-highlights/`,
        edit: (id) => `/faculty-highlights/${id}`,
        delete: (id) => `/faculty-highlights/${id}`,
      },
    },
    blog: {
      authors: {
        list: "/blog-authors/",
        details: (id) => `/blog-authors/${id}/`,
        create: `/blog-authors/`,
        edit: (id) => `/blog-authors/${id}/`,
      },
      category: {
        list: "/blog-categories/",
        details: (id) => `/blog-categories/${id}`,
        edit: (id) => `/blog-categories/${id}`,
        create: `/blog-categories/`,
      },
      tags: {
        list: "/blog-tags/",
        details: (id) => `/blog-tags/${id}`,
        create: `/blog-tags/`,
        edit: (id) => `/blog-tags/${id}/`,
        delete: (id) => `/blog-tags/${id}/`,
      },
      posts: {
        list: "/blog-posts/",
        details: (id) => `/blog-posts/${id}/`,
        create: `/blog-posts/`,
        edit: (id) => `/blog-posts/${id}/`,
        delete: (id) => `/blog-posts/${id}/`,
      },
    },
    courses: {
      Modules: {
        list: "/course-modules/",
        details: (id) => `/course-modules/${id}/`,
        create: `/course-modules/`,
        edit: (id) => `/course-modules/${id}/`,
        delete: (id) => `/course-modules/${id}/`,
      },
      list: "/courses/",
      details: (id) => `/courses/${id}/`,
      create: `/courses/`,
      edit: (id) => `/courses/${id}/`,
      delete: (id) => `/courses/${id}/`,
    },
    pages: {
      homePage: {
        list: "/home-pages/",
        details: (id) => `/home-pages/${id}/`,
        create: `/home-pages/`,
        edit: (id) => `/home-pages/${id}/`,
        delete: (id) => `/home-pages/${id}/`,
      },
      aboutPage: {
        list: "/about-pages/",
        details: (id) => `/about-pages/${id}/`,
        create: `/about-pages/`,
        edit: (id) => `/about-pages/${id}/`,
        delete: (id) => `/about-pages/${id}/`,
      },
      heroSlides: {
        list: "/hero-slides/",
        details: (id) => `/hero-slides/${id}/`,
        create: `/hero-slides/`,
        edit: (id) => `/hero-slides/${id}/`,
        delete: (id) => `/hero-slides/${id}/`,
      },
      aboutHeroSlides: {
        list: "/about-hero-slides/",
        details: (id) => `/about-hero-slides/${id}/`,
        create: `/about-hero-slides/`,
        edit: (id) => `/about-hero-slides/${id}/`,
        delete: (id) => `/about-hero-slides/${id}/`,
      },
      coreValues: {
        list: "/core-values/",
        details: (id) => `/core-values/${id}/`,
        create: `/core-values/`,
        edit: (id) => `/core-values/${id}/`,
        delete: (id) => `/core-values/${id}/`,
      },
      campusFacilities: {
        list: "/campus-facilities/",
        details: (id) => `/campus-facilities/${id}/`,
        create: `/campus-facilities/`,
        edit: (id) => `/campus-facilities/${id}/`,
        delete: (id) => `/campus-facilities/${id}/`,
      },
      faqs: {
        list: "/faqs/",
        details: (id) => `/faqs/${id}/`,
        create: `/faqs/`,
        edit: (id) => `/faqs/${id}/`,
        delete: (id) => `/faqs/${id}/`,
      },
      upcomingEvents: {
        list: "/upcoming-events/",
        details: (id) => `/upcoming-events/${id}/`,
        create: `/upcoming-events/`,
        edit: (id) => `/upcoming-events/${id}/`,
        delete: (id) => `/upcoming-events/${id}/`,
      },

      testimonials: {
        list: "/testimonials/",
        details: (id) => `/testimonials/${id}/`,
        create: `/testimonials/`,
        edit: (id) => `/testimonials/${id}/`,
        delete: (id) => `/testimonials/${id}/`,
      },
      whyChooseFeatures: {
        list: "/why-choose-features/",
        details: (id) => `/why-choose-features/${id}/`,
        create: `/why-choose-features/`,
        edit: (id) => `/why-choose-features/${id}/`,
        delete: (id) => `/why-choose-features/${id}/`,
      },
    },
    scholarship: {
      listPages: {
        list: "/scholarship-list-pages/",
        details: (id) => `/scholarship-list-pages/${id}/`,
        create: `/scholarship-list-pages/`,
        edit: (id) => `/scholarship-list-pages/${id}/`,
        delete: (id) => `/scholarship-list-pages/${id}/`,
      },
      list: "/scholarships/",
      details: (id) => `/scholarships/${id}/`,
      create: `/scholarships/`,
      edit: (id) => `/scholarships/${id}/`,
      delete: (id) => `/scholarships/${id}/`,
    },
    staff: {
      category: {
        list: "/staff-categories/",
        details: (id) => `/staff-categories/${id}/`,
        create: `/staff-categories/`,
        edit: (id) => `/staff-categories/${id}/`,
        delete: (id) => `/staff-categories/${id}/`,
      },
      position: {
        list: "/staff-positions/",
        details: (id) => `/staff-positions/${id}/`,
        create: `/staff-positions/`,
        edit: (id) => `/staff-positions/${id}/`,
        delete: (id) => `/staff-positions/${id}/`,
      },
      list: "/staff/",
      details: (id) => `/staff/${id}/`,
      create: `/staff/`,
      edit: (id) => `/staff/${id}/`,
      delete: (id) => `/staff/${id}/`,
    },
    admission: {
      pages: {
        list: "/admission-pages/",
        details: (id) => `/admission-pages/${id}/`,
        create: `/admission-pages/`,
        edit: (id) => `/admission-pages/${id}/`,
        delete: (id) => `/admission-pages/${id}/`,
      },
      whyChooseFeatures: {
        list: "/addmission/why-choose-features/",
        details: (id) => `/addmission/why-choose-features/${id}/`,
        create: `/addmission/why-choose-features/`,
        edit: (id) => `/addmission/why-choose-features/${id}/`,
        delete: (id) => `/addmission/why-choose-features/${id}/`,
      },
      requirements:{
        list: "/admission-requirements/",
        details: (id) => `/admission-requirements/${id}/`,
        create: `/admission-requirements/`,
        edit: (id) => `/admission-requirements/${id}/`,
        delete: (id) => `/admission-requirements/${id}/`,
      },
      requirementsItems:{
        list: "/admission-requirement-items/",
        details: (id) => `/admission-requirement-items/${id}/`,
        create: `/admission-requirement-items/`,
        edit: (id) => `/admission-requirement-items/${id}/`,
        delete: (id) => `/admission-requirement-items/${id}/`,
      },
      steps:{
        list: "/application-steps/",
        details: (id) => `/application-steps/${id}/`,
        create: `/application-steps/`,
        edit: (id) => `/application-steps/${id}/`,
        delete: (id) => `/application-steps/${id}/`,
      },
      importantDates:{
        list: "/important-dates/",
        details: (id) => `/important-dates/${id}/`,
        create: `/important-dates/`,
        edit: (id) => `/important-dates/${id}/`,
        delete: (id) => `/important-dates/${id}/`,
      }
    },
  },
};
